In [30]:
import numpy as np
def gini(actual, pred, cmpcol = 0, sortcol = 1):
    assert( len(actual) == len(pred) )
    all = np.asarray(np.c_[ actual, pred, np.arange(len(actual)) ], dtype=np.float)
    all = all[ np.lexsort((all[:,2], -1*all[:,1])) ]
    totalLosses = all[:,0].sum()
    giniSum = all[:,0].cumsum().sum() / totalLosses
 
    giniSum -= (len(actual) + 1) / 2.
    return giniSum / len(actual)


print gini([1,0,1,0],[0.7,0.2,0.8,0.3])
print gini([1,0,1,0],[1,0,1,0])
print gini([1,0,1,0],[0.5,0.5,0.5,0.5])
print gini([1,0,1,0],[0.2,0.7,0.8,0.5])
print gini([1,0,1,0],[0,1,0,1])

0.25
0.25
0.125
0.0
-0.25


In [13]:
import numpy as np
def gini(actual, pred, cmpcol = 0, sortcol = 1):
    assert( len(actual) == len(pred) )
    all = np.asarray(np.c_[ actual, pred, np.arange(len(actual)) ], dtype=np.float)
    print all
    all = all[ np.lexsort((all[:,2], -1*all[:,1])) ]
    print all
    totalLosses = all[:,0].sum()
    print totalLosses
    giniSum = all[:,0].cumsum().sum() / totalLosses
    print giniSum
 
    giniSum -= (len(actual) + 1) / 2.
    return giniSum / len(actual)


print gini([1,0,1,0],[0.7,0.2,0.8,0.3])
print gini([1,0,1,0],[1,0,1,0])
print gini([1,0,1,0],[0.5,0.5,0.5,0.5])
print gini([1,0,1,0],[0.2,0.7,0.8,0.5])
print gini([1,0,1,0],[0,1,0,1])

[[ 1.   0.7  0. ]
 [ 0.   0.2  1. ]
 [ 1.   0.8  2. ]
 [ 0.   0.3  3. ]]
[[ 1.   0.8  2. ]
 [ 1.   0.7  0. ]
 [ 0.   0.3  3. ]
 [ 0.   0.2  1. ]]
2.0
3.5
0.25
[[ 1.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  1.  2.]
 [ 0.  0.  3.]]
[[ 1.  1.  0.]
 [ 1.  1.  2.]
 [ 0.  0.  1.]
 [ 0.  0.  3.]]
2.0
3.5
0.25
[[ 1.   0.5  0. ]
 [ 0.   0.5  1. ]
 [ 1.   0.5  2. ]
 [ 0.   0.5  3. ]]
[[ 1.   0.5  0. ]
 [ 0.   0.5  1. ]
 [ 1.   0.5  2. ]
 [ 0.   0.5  3. ]]
2.0
3.0
0.125
[[ 1.   0.2  0. ]
 [ 0.   0.7  1. ]
 [ 1.   0.8  2. ]
 [ 0.   0.5  3. ]]
[[ 1.   0.8  2. ]
 [ 0.   0.7  1. ]
 [ 0.   0.5  3. ]
 [ 1.   0.2  0. ]]
2.0
2.5
0.0
[[ 1.  0.  0.]
 [ 0.  1.  1.]
 [ 1.  0.  2.]
 [ 0.  1.  3.]]
[[ 0.  1.  1.]
 [ 0.  1.  3.]
 [ 1.  0.  0.]
 [ 1.  0.  2.]]
2.0
1.5
-0.25


In [29]:
import numpy as np
import pandas as pd
def gini(actual, pred):
    df = pd.DataFrame({'actual':actual,'pred':pred})\
            .reset_index()\
            .sort_values(['pred','index'],ascending=[False,True])\
            .astype('float')
    
    ginisum = df["actual"].cumsum().sum()/df["actual"].sum()
    ginisum -= (len(df)+1.)/2
    
    return ginisum/len(actual)
    


print gini([1,0,1,0],[0.7,0.2,0.8,0.3])
print gini([1,0,1,0],[1,0,1,0])
print gini([1,0,1,0],[0.5,0.5,0.5,0.5])
print gini([1,0,1,0],[0.2,0.7,0.8,0.5])
print gini([1,0,1,0],[0,1,0,1])

0.25
0.25
0.125
0.0
-0.25


In [31]:
from keras import backend as K

In [40]:
a = np.array([1,0,1,0])
b = np.array([0.7,0.2,0.8,0.3])

In [43]:
actual = K.cast_to_floatx(a)
pred = K.cast_to_floatx(b)
print actual, pred

[ 1.  0.  1.  0.] [ 0.69999999  0.2         0.80000001  0.30000001]


In [54]:
ind = K.cast_to_floatx(range(len(actual)))

m = K.cast_to_floatx(np.asarray([actual,pred,range(len(actual))]).T)
m

array([[ 1.        ,  0.69999999,  0.        ],
       [ 0.        ,  0.2       ,  1.        ],
       [ 1.        ,  0.80000001,  2.        ],
       [ 0.        ,  0.30000001,  3.        ]], dtype=float32)

In [ ]:
K.

In [ ]:
def gini(actual, pred):
    assert( len(actual) == len(pred) )
    all = np.asarray(np.c_[ actual, pred, np.arange(len(actual)) ], dtype=np.float)
    print all
    all = all[ np.lexsort((all[:,2], -1*all[:,1])) ]
    print all
    totalLosses = all[:,0].sum()
    print totalLosses
    giniSum = all[:,0].cumsum().sum() / totalLosses
    print giniSum
 
    giniSum -= (len(actual) + 1) / 2.
    return giniSum / len(actual)